version: "3"
services:
  web:
    build: .
    ports:
        - "8080:8080"
    depends_on:
        - mongo
    env_file:
        - ./.env.example
  mongo:
    image: mongo
    ports:
    - "27017:27017"